<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Vehicule;

class VehiculeSeeder extends Seeder
{
    public function run(): void
    {
        $vehicules = [
            [
                'matricule'        => '50963-20-أ',
                'marque'           => 'Renault',
                'modele'           => 'Clio',
                'annee'            => 2025,
                'type_transport'   => 'citadine',
                'nombre_passagers' => 5,
                'capacite_bagages' => 2,
                'tarif_journalier' => 300.00,
                'kilometrage'      => 12000,
                'couleur'          => 'Bleu',
                'boite_vitesse'    => 'automatique',
                'carburant'        => 'diesel',
                'statut'           => 'disponible',
            ],
            [
                'matricule'        => '12487-20-أ',
                'marque'           => 'Renault',
                'modele'           => 'Kardian',
                'annee'            => 2025,
                'type_transport'   => 'suv',
                'nombre_passagers' => 5,
                'capacite_bagages' => 4,
                'tarif_journalier' => 500.00,
                'kilometrage'      => 8000,
                'couleur'          => 'Bleu',
                'boite_vitesse'    => 'automatique',
                'carburant'        => 'diesel',
                'statut'           => 'disponible',
            ],
            [
                'matricule'        => '33601-20-أ',
                'marque'           => 'Renault',
                'modele'           => 'Megane',
                'annee'            => 2024,
                'type_transport'   => 'berline',
                'nombre_passagers' => 5,
                'capacite_bagages' => 3,
                'tarif_journalier' => 400.00,
                'kilometrage'      => 22000,
                'couleur'          => 'Blanc',
                'boite_vitesse'    => 'manuelle',
                'carburant'        => 'diesel',
                'statut'           => 'disponible',
            ],
            [
                'matricule'        => '89542-20-أ',
                'marque'           => 'Renault',
                'modele'           => 'Trafic',
                'annee'            => 2025,
                'type_transport'   => 'utilitaire',
                'nombre_passagers' => 9,
                'capacite_bagages' => 8,
                'tarif_journalier' => 800.00,
                'kilometrage'      => 15000,
                'couleur'          => 'Noir',
                'boite_vitesse'    => 'manuelle',
                'carburant'        => 'diesel',
                'statut'           => 'disponible',
            ],
            [
                'matricule'        => '41029-20-أ',
                'marque'           => 'Dacia',
                'modele'           => 'Duster',
                'annee'            => 2025,
                'type_transport'   => 'suv',
                'nombre_passagers' => 5,
                'capacite_bagages' => 4,
                'tarif_journalier' => 500.00,
                'kilometrage'      => 9500,
                'couleur'          => 'Gris Nardo',
                'boite_vitesse'    => 'automatique',
                'carburant'        => 'diesel',
                'statut'           => 'disponible',
            ],
            [
                'matricule'        => '67233-20-أ',
                'marque'           => 'Dacia',
                'modele'           => 'Logan',
                'annee'            => 2023,
                'type_transport'   => 'berline',
                'nombre_passagers' => 5,
                'capacite_bagages' => 3,
                'tarif_journalier' => 300.00,
                'kilometrage'      => 38000,
                'couleur'          => 'Blanc',
                'boite_vitesse'    => 'manuelle',
                'carburant'        => 'diesel',
                'statut'           => 'disponible',
            ],
            [
                'matricule'        => '15890-20-أ',
                'marque'           => 'Dacia',
                'modele'           => 'Sandero',
                'annee'            => 2024,
                'type_transport'   => 'citadine',
                'nombre_passagers' => 5,
                'capacite_bagages' => 2,
                'tarif_journalier' => 300.00,
                'kilometrage'      => 18000,
                'couleur'          => 'Blanc',
                'boite_vitesse'    => 'manuelle',
                'carburant'        => 'diesel',
                'statut'           => 'disponible',
            ],
            [
                'matricule'        => '92455-20-أ',
                'marque'           => 'Dacia',
                'modele'           => 'Stepway',
                'annee'            => 2024,
                'type_transport'   => 'citadine',
                'nombre_passagers' => 5,
                'capacite_bagages' => 3,
                'tarif_journalier' => 400.00,
                'kilometrage'      => 21000,
                'couleur'          => 'Jaune Ambre',
                'boite_vitesse'    => 'automatique',
                'carburant'        => 'diesel',
                'statut'           => 'disponible',
            ],
            [
                'matricule'        => '28314-20-أ',
                'marque'           => 'Hyundai',
                'modele'           => 'Accent',
                'annee'            => 2023,
                'type_transport'   => 'berline',
                'nombre_passagers' => 5,
                'capacite_bagages' => 3,
                'tarif_journalier' => 300.00,
                'kilometrage'      => 41000,
                'couleur'          => 'Gris Nardo',
                'boite_vitesse'    => 'automatique',
                'carburant'        => 'diesel',
                'statut'           => 'disponible',
            ],
            [
                'matricule'        => '55780-20-أ',
                'marque'           => 'Hyundai',
                'modele'           => 'Tucson',
                'annee'            => 2025,
                'type_transport'   => 'suv',
                'nombre_passagers' => 5,
                'capacite_bagages' => 5,
                'tarif_journalier' => 600.00,
                'kilometrage'      => 7000,
                'couleur'          => 'Vert Cyprès',
                'boite_vitesse'    => 'automatique',
                'carburant'        => 'diesel',
                'statut'           => 'disponible',
            ],
            [
                'matricule'        => '70126-20-أ',
                'marque'           => 'Peugeot',
                'modele'           => '208',
                'annee'            => 2022,
                'type_transport'   => 'citadine',
                'nombre_passagers' => 5,
                'capacite_bagages' => 2,
                'tarif_journalier' => 300.00,
                'kilometrage'      => 55000,
                'couleur'          => 'Blanc',
                'boite_vitesse'    => 'automatique',
                'carburant'        => 'diesel',
                'statut'           => 'disponible',
            ],
            [
                'matricule'        => '44908-20-أ',
                'marque'           => 'Peugeot',
                'modele'           => '2008',
                'annee'            => 2024,
                'type_transport'   => 'suv',
                'nombre_passagers' => 5,
                'capacite_bagages' => 4,
                'tarif_journalier' => 500.00,
                'kilometrage'      => 19000,
                'couleur'          => 'Gris Nardo',
                'boite_vitesse'    => 'automatique',
                'carburant'        => 'diesel',
                'statut'           => 'disponible',
            ],
        ];

        foreach ($vehicules as $data) {
            Vehicule::create($data);
        }
    }
}